"""Refactor documents for RAG chunks

Revision ID: 54e6eeabb697
Revises: ce9e15d962fb
Create Date: 2025-12-22 11:09:22.124756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54e6eeabb697'
down_revision: Union[str, Sequence[str], None] = 'ce9e15d962fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('assignment_allowed', sa.Boolean(), nullable=False),
    sa.Column('embedding_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('courses_course_run_id_key'), 'courses', type_='unique')
    op.drop_column('courses', 'course_run_id')
    op.add_column('documents', sa.Column('session_id', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('source_uri', sa.String(), nullable=False))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'source_uri')
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'session_id')
    op.add_column('courses', sa.Column('course_run_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('courses_course_run_id_key'), 'courses', ['course_run_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
